.gitignore, composer.json, composer.lock, config/bundles.php, config/packages/twig.yaml, config/routes/dev/twig.yaml, symfony.lock, templates/base.html.twig
=> Add twig library #7

.env.dist, composer.json, composer.lock, config/bundles.php, config/packages/doctrine.yaml, config/packages/doctrine_migrations.yaml, config/packages/prod/doctrine.yaml, phpunit.xml.dist, symfony.lock
Install doctrine from orm-pack.
Closes #8
=> #8 - Add doctrine

composer.json, composer.lock, config/bundles.php, symfony.lock
In order to be able to generate entities and repositories using cli commands
As developers
We need to have maker bundle available 
Closes #9
=> #9 - Add maker bundle

composer.json, composer.lock, config/bundles.php, config/packages/dev/easy_log_handler.yaml, config/packages/dev/monolog.yaml, config/packages/dev/web_profiler.yaml, config/packages/prod/monolog.yaml, config/packages/test/web_profiler.yaml, config/routes/dev/web_profiler.yaml, symfony.lock
In order to be able to debug various problems
As developers
We need to have debug pack
=> #10 - Add debug pack

.env.dist, composer.json, composer.lock, config/bundles.php, config/packages/dev/swiftmailer.yaml, config/packages/swiftmailer.yaml, config/packages/test/swiftmailer.yaml, phpunit.xml.dist, symfony.lock
Add mailer to project
Closes #12
=> 12 add mailer

composer.json, composer.lock, symfony.lock
@kristijanzg couldn't create a PR for some strange reason, so I'm helping him out. We should probably ping @msvrtan for assistance. Not sure if there's some kind of a problem with permissions again.
Kristijan templating to our project, which is really nice.
Closes #13
=> #13 - Add templating dependancy

composer.json, composer.lock, config/packages/translation.yaml, config/services.yaml, symfony.lock
Added new symfony/translation dependancy required for FoSUserBundle
=> #14 Add translation dependancy

composer.json, composer.lock, config/bundles.php, config/packages/fos_user.yaml, config/packages/framework.yaml, config/packages/security.yaml, config/packages/test/framework.yaml, config/routes.yaml, src/Entity/User.php, src/Repository/UserRepository.php, symfony.lock
In order for customers to use our site
We need to allow them to register and log in
I'we tried to keep commits nice and small for easier reviewing
In vagrant:
1) Run `php composer.phar install` to fetch changes
2) Run `php bin/console doctrine:schema:update --force` to update database
In browser:
3) Go to `/register` and register your self (you will need to click log off as it's set up to automatically log you in after registration)
4) Go to `/login` and login using the username/password you set up
Closes #41
=> Login & registration: adding FOSUserBundle

templates/bundles/FOSUserBundle/Security/login.html.twig, templates/bundles/FOSUserBundle/Security/login_content.html.twig, templates/bundles/FOSUserBundle/layout.html.twig
Added bootstrap3 to default fos:user layout template.
Closes #43
=> Add Bootstrap to fos:user templates

templates/bundles/FOSUserBundle/Registration/register_content.html.twig
=> Registration template

src/Migrations/Version20180113111523.php
=> Add user table migration

config/bundles.php, symfony.lock
=> Add fixtures to bundles.php config

composer.json, composer.lock, symfony.lock
In order to be able to test our code more efficiently
As developers
We need to use mockery.
This will install mockery/mockery, v^1.0
**NOTE:**
This is rebased with #61
=> [Development Tools] - Add mockery

templates/base.html.twig
Adding Bootstrap4 CDN to default template.
So stylish, such wow!
Closes #57  
**In reference to #58**
=> Add bootstrap to base template

src/Controller/HomepageController.php, src/Kernel.php, src/Migrations/Version20180113111523.php, tests/Controller/HomepageControllerTest.php
Before enforcing php-cs-fixer to be run project wide on CircleCI, we
first need to clean up all the files in our code base.
=> Issue #70 - Run php-cs-fixer project wide

templates/base.html.twig, templates/partials/header.html.twig
I'll create new issue / PR for login, logout buttons etc after we build valid routes for that.
Closes #59
=> Add header partial with navbar, include it in base twig.

src/DataFixtures/ORM/PostsFixtures.php
We need some dummy/testing data in our databases while developing, so
I'm adding two very simple dummy posts.
=> Issue #73 - Add data fixtures for Post entity

src/Entity/Post.php, src/Migrations/Version20180116204748.php, tests/Entity/PostTest.php
This will create a basic implementation of the Post entity, adding doctrine annotations, and creating the migration file for it.
As we progress with development, we'll need to revisit the entity and add new references for new entities (e.g. [Category](#31), [Author/User](#35), [Comment](#32)) to replace current string representations.
~~_TODO:_~~ **(WILL BE NEW PR)**
- ~~add fixtures for Post~~
- ~~add Post repository~~
- ~~add tests for Post repository~~
**NOTE:**
this is rebased with #62 
Closes #30
=> Issue #30 - [Bulletin Board] Implement Post

.gitignore, composer.json, composer.lock, config/bundles.php, symfony.lock
Add symfony server component as dev dependency
Closes #66
=> Add server

config/services.yaml, src/DataFixtures/ORM/PostsFixtures.php
Forgot to enable loading of doctrine fixtures.
@flackovic you should've caught that one... 😛 
This will also add named references to Post fixture objects.
Closes #77
=> Issue #77 - Can't load Doctrine Fixtures

src/DataFixtures/ORM/UsersFixtures.php
=> Create users fixtures for 2 roles, admin and visitor

src/Controller/HomepageController.php
Clean up controller and returns template
=> Clean homepage controller and make it actually return homepage template

src/Entity/Category.php, src/Entity/Post.php, src/Migrations/Version20180122194958.php, tests/Entity/CategoryTest.php, tests/Entity/PostTest.php
This will implement Post Category entity, based on corresponding tests.
A migration file is also created for this entity.
TODO:
- ~~add references from Post entity to Post Category~~ ✅ 
~~- add PostCategoryRepository~~ ❌ _will be implemented in a separate PR_
~~- add PostCategoryRepository tests~~  ❌ _will be implemented in a separate PR_
Closes #31
=> Issue #31 [Bulletin Board] - Create Post Category

src/Controller/HomepageController.php, src/DataFixtures/ORM/UsersFixtures.php
fixing stuff we missed earlier.
=> project wide php-cs-fixer

src/Controller/HomepageController.php, src/DataFixtures/ORM/UsersFixtures.php, src/Repository/CategoryRepository.php
_In order to have a structured and easy to use way of retrieving Post entities_
_As developers_
_We need to have a repository of Post entities at our disposal._
This PR will add a PostCategory Repository.
Closes #90
=> Issue #90 [Bulletin Board] Add a repository class for PostCategory Entity

src/DataFixtures/ORM/PostCategoryFixtures.php, src/DataFixtures/ORM/PostsFixtures.php, src/Entity/Post.php, src/Entity/PostComment.php, src/Entity/User.php, src/Migrations/Version20180125210803.php, src/Migrations/Version20180125231331.php, tests/Entity/PostCommentTest.php, tests/Entity/PostTest.php
Implement PostComment entity based on tests, add a migration file, and create data fixtures.
Post entity gets an update to keep track of its belonging comments, and User entity gets a reference to all of their belonging comments as well.
Closes #32 
Closes #95 
~~P.S. - something went terribly wrong with this rebase.~~
~~@msvrtan waiting for your help on this one 🙂~~
=> Issue #32 [Bulletin Board] - Implement Post Comment

composer.lock, src/Entity/User.php
Currently a user has administrative privileges simply by having a flag set to true.
This needs further consideration and work.
Closes #34
=> Issue #34 [Bulletin Board] - Create Administration Staff basics

src/Entity/Post.php, src/Migrations/Version20180125222237.php, tests/Entity/PostTest.php
Post can be archived, so we need to introduce a new property that will enable marking certain posts as archived.
Tests have been added.
Closes #33
=> Issue #33 [Bulletin Board] - Define what a Post Archive represents

src/DataFixtures/ORM/PostCommentsFixtures.php
PostComment entity needs fixtures
Closes #106
=> Issue #106 [Bulletin Board] - Add fixtures for PostComment entity

src/DataFixtures/ORM/PostsFixtures.php, src/Entity/Post.php
We had a broken relation between Post and Category (when trying to map entities to db).
Pinging Yoda @msvrtan for help : how were tests supposed to look (and test what exactly) to catch this early on, and signal there was a problem in defining relations between Post and Category?
Closes #109
=> Issue #109 [Bulletin Board] -  Fix the relation between Post and Category

phpunit.xml.dist
In order to allow phpunit to connect to test db, we need to add a new
DSN to phpunit.xml
Closes #113
=> Issue #113 [Infrastructure] - Cconnect PhpUnit to test db

phpunit.xml.dist, src/Entity/Post.php, src/Migrations/Version20180208170023.php, tests/Entity/PostTest.php
=> Feature active property

phpunit.xml.dist, tests/Route/HomepageControllerRoutesTest.php, tests/Route/PostControllerRoutesTest.php
=> Feature add route tests

circle.yml, tests/Repository/PostRepositoryTest.php
In order to make sure we have set up Doctrine annotations and relations between entities correctly
As developers
We need to add tests to PostRepository
Closes #89
=> Issue #89 [Bulletin Board] - Add Tests for PostRepository

circle.yml
We need to seed the database on CircleCI with data fixtures in order
to have passing tests that deal with db interactions.
Closes #120
=> Issue #120 [Infra] - Run DataFixtures on CircleCI

circle.yml, phpunit.xml.dist
In order to track out test code coverage
Lets create code coverage reports
And ship them to codecov.io
=> Code coverage

circle.yml, phpmd.xml, src/DataFixtures/ORM/PostsFixtures.php
In order to use PHPMD in our dev work and ensure our code meets certain quality standards
As developers
We need to set up configuration for PHPMD
And run it automatically on CircleCI
Closes #124
=> Issue #124 [PHPMD] - Set up PHPMD

templates/partials/navbar.html.twig
Add logout button if user is authenticated.
Look and feel will be changed in future, for now its just functionality
Closes #132
=> Add logout button

src/Repository/CategoryRepository.php
I think this is pre-generated by maker bundle, we dont really need this
=> CategoryRepository: Remove commented out code

src/Entity/Post.php
=> Fix return type

src/DataFixtures/ORM/PostCategoryFixtures.php, src/DataFixtures/ORM/PostCommentsFixtures.php, src/DataFixtures/ORM/PostsFixtures.php, src/Entity/Category.php, src/Entity/Post.php, src/Entity/PostComment.php, tests/Entity/CategoryTest.php, tests/Entity/PostCommentTest.php, tests/Entity/PostTest.php
Since we need to use EasyAdminBundle and we will eventually need to create various forms for frontend, we should move to using setters instead of constructor injection in entities.
Closes #130
=> Issue #130 - Remove construct parameters

src/Controller/HomepageController.php, src/Controller/PostController.php
Instead of extending Symfony base controller, lets inject dependencies in, use @Template ...
This makes code less dependant on Symfony and explicitly
=> Use templating

README.md
=> Add link to production on top of README file

composer.lock, config/bundles.php, config/packages/easy_admin.yaml, config/routes/easy_admin.yaml, symfony.lock
Bundle added.
run `composer install` to install bundle
then `./bin/console assets:install --symlink` to install assets if not
Closes #140
=> Issue 140 admin bundle

src/DataFixtures/ORM/UsersFixtures.php, src/Entity/User.php, tests/Entity/UserTest.php
User entity had low tests coverage, so we need to improve it.
This will add new tests for User, introduce new User fixture (for a regular user), and fix wrong return type declarations on User's Comments and Posts getter methods.
Closes #104
=> Issue #104 [Bulletin Board] - Improve tests for User entity

config/packages/security.yaml, tests/Controller/HomepageControllerTest.php, tests/Route/HomepageControllerRoutesTest.php, tests/Route/PostControllerRoutesTest.php
Add route protection, only logged in users can access site.
To test: try /posts as guest
=> Protect routes
